name: Test Config Workflow

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-config:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Test Step
      run: echo "This is a test for the test_config.yml workflow"
