name: Test Config Workflow

on:
  workflow_dispatch:  # Enables manual runs from GitHub Actions UI
  repository_dispatch:  # Allows external triggers (e.g., from Zapier)
    types: [zapier_trigger]  # Matches the event_type sent from Zapier

jobs:
  test-config:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Test Step
      run: echo "This is a test for the test_config.yml workflow"

  test-google-sheets:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set environment variable
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: |
        echo "$GOOGLE_SHEETS_CREDENTIALS" > credentials.json
        python read_google_sheets.py
