name: Fetch and Commit Google Sheets Data

permissions:
  contents: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [zapier_trigger]

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Set up Google Sheets credentials
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: echo "$GOOGLE_SHEETS_CREDENTIALS" > credentials.json

      - name: Fetch data from Google Sheets
        run: python read_google_sheets.py

      - name: Check for changes in output.json
        run: |
          git add output.json
          if ! git diff --cached --exit-code; then
            git commit -m 'Update output.json with latest Google Sheets data'
            git push
          else
            echo "No changes detected in output.json; skipping commit."
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output.json
          git commit -m 'Add latest Google Sheets data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
